apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: isiqh2vhg-nodejs 
  janus-idp.io/tekton: isiqh2vhg-nodejs
  backstage.io/kubernetes-id: isiqh2vhg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: isiqh2vhg-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml