apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: isiqh2vhg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: isiqh2vhg-nodejs 
  name: isiqh2vhg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: isiqh2vhg-nodejs 
